### DISCUSSION TITLE
Keda http addon strips off Authorization header from request

### DISCUSSION THREAD

**Discussion by arsalen536** [kedacore/http-add-on#1115] [General]
I'm new to KEDA and am trying to use the `keda-add-ons-http scalers` to scale my microservices application on Kubernetes based on incoming HTTP requests. My application is deployed behind an Nginx ingress controller.

I've set up an `HTTPScaledObject` for each service that I want to scale, and everything works as expected: the requests trigger the scaling of the target services. However, I’ve encountered an issue where the `Authorization` header is missing from the requests that reach my application. Other headers are preserved correctly.

Here’s my setup:
### KEDA HTTPScaledObject Configuration:
```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: example-service-http-scaled-object
    namespace: example
spec:
    hosts:
        - example.com
    pathPrefixes:
        - /example
    scaleTargetRef:
        name: example-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: example-service
        port: 80
    replicas:
        min: 0
        max: 10
    scaledownPeriod: 3
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 100
            window: 1m
```
### Service of type ExternalName:
```
apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy
  namespace: example
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda-add-ons-http.svc.cluster.local
```
### Ingress Object:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ..
  name: example-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: 8080
        path: /
        pathType: Prefix
      - backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: 8080
        path: /example
        pathType: Prefix
        ..
```
The scaling works, but the `Authorization` header seems to be stripped out somewhere between the ingress and the final service. Could this be an issue with the Nginx ingress, KEDA operator, or interceptor? Any advice on how to debug or fix this issue would be greatly appreciated.
