### DISCUSSION TITLE
Add annotations to interceptor service

### DISCUSSION THREAD

**Discussion by rwkarg** [kedacore/http-add-on#218] [Ideas]
This issue (#36) has been closed but I don't see a way to currently add annotations to the interceptor service.

The specific use case we have is using [autoneg-controller](https://github.com/GoogleCloudPlatform/gke-autoneg-controller) to add workload instances from multiple clusters as backends to a single Load Balancer. In GCP, this requires that the service (would be the interceptor service) has two annotations to create the Network Endpoint Group (NEG) and to associate that NEG with a Backend Service on the Load Balancer (not important what it does, just that we need annotations on the interceptor service).

Looks like #206 may complicate this, if there is only one service. We can't add the annotations to individual services any more for `autoneg-controller` to work in that case.

Is the multi-tenant interceptor something that can be opted out of?

**Comment by tomkerkhove** [comment]
That's good input for #183 / @arschles @yaron2.

I think the sweet spot here is being able to install dedicated interceptors with multi-tenant interceptor as default. This would allow you to have 1 KEDA HTTP installation, but tailored to your need since multiple installations won't work  due to only-one-operator limitation.

**Reply by tomkerkhove** [reply]
Maybe an annotation on the `HTTPScaledObject` might be a good fit here - For example `httpscaledobject.keda.sh/dedicated-deployment: true` or so

**Reply by arschles** [reply]
I think we can add configuration for doing dedicated interceptors. It'll be easier to add that back in after doing #206, yes. Another option to to add a section to the `HTTPScaledObject`, rather than an annotation on it, to set annotations...

**Reply by tomkerkhove** [reply]
That's OK for me as well!

How would that look like then?

**Reply by arschles** [reply]
Here's one idea:

```
spec:
    host: myhost.com
    scaleTargetRef:
        deployment: xkcd
        service: xkcd
        port: 8080
    replicas:
        min: 5
        max: 10
    deployment:
        type: dedicated
        annotations:
            interceptor:
                key1: val1
                key2: val2
````

**Reply by tomkerkhove** [reply]
Something I was thinking about - What if this would be a separate CRD.

The reason is that while you would not want to use the default (shared) interceptor, maybe you want to have a dedicated interceptor that is shared with your 2 apps, which only you own.

So if you would have 5 apps - 3 of them use the shared one, the other 2 share a dedicated deployment through a `requestInterceptorRef: <name>` which is linked to a CRD object

All annotations that are on the interceptor CRD, are applied on the deployment.

**Reply by arschles** [reply]
@tomkerkhove something like a CRD to track interceptor infrastructure? would the operator be responsible for creating the new interceptor infrastructure when a new CRD was created?

also, I think scalers and interceptors should be 1:1. WDYT?

**Reply by tomkerkhove** [reply]
> @tomkerkhove something like a CRD to track interceptor infrastructure? would the operator be responsible for creating the new interceptor infrastructure when a new CRD was created?

Yes.

**Reply by tomkerkhove** [reply]
> also, I think scalers and interceptors should be 1:1. WDYT?

I don't have a preference on this, I'm not experienced enough with the details - Sorry :/

**Reply by arschles** [reply]
>I don't have a preference on this, I'm not experienced enough with the details - Sorry :/

Not a problem. Allowing a scaler to interact with multiple interceptor fleets would introduce complexity that I think is needless, so I'm inclined to tightly couple a CRD, scaler and interceptor fleet. What do you think of this rough CRD schema?

```yaml
kind: HTTPScalingInfrastructure
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: MyApp
spec:
    interceptor:
        serviceType: ClusterIP # this is the default, but you can specify other service types
        minReplicas: 10
        maxReplicas: 100
        annotations:
            key1: val1
    scaler:
        serviceType: ClusterIP # same as spec.interceptor.serviceType
        annotations:
            key1: val1
```

The official helm chart can install one of these, and then all `HTTPScaledObjects` need to either specify their own custom one, or it defaults to the chart-installed one. Here's how you might specify your own:

```yaml
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ include "xkcd.fullname" . }}
spec:
    scalingInfrastructure: # IF YOU DON'T SPECIFY THIS, IT DEFAULTS TO ONE THE CHART INSTALLED (THE CHART CONFIGURES THE HTTP ADDON OPERATOR WITH THIS DEFAULT)
        name: MyApp # THIS IS WHERE YOU SPECIFY YOUR OWN SCALING INFRA
        namespace: othernamespace # YOU CAN RUN SCALING INFRA IN A DIFFERENT NAMESPACE IF YOU WANT, BUT IF YOU DON'T SPECIFY THIS, IT DEFAULTS TO THE CURRENT NAMESPACE
    host: {{ .Values.host }}
    scaleTargetRef:
        deployment: {{ include "xkcd.fullname" . }}
        service: {{ include "xkcd.fullname" . }}
        port: 8080
    replicas:
        min: {{ .Values.autoscaling.http.minReplicas }}
        max: {{ .Values.autoscaling.http.maxReplicas }}
```

WDYT?
