### DISCUSSION TITLE
How to combine this with other Keda triggers

### DISCUSSION THREAD

**Discussion by tdnguyen6** [kedacore/http-add-on#455] [Q&A]
I want to use multiple triggers for my deployment. How can I combine this tool with other Keda triggers so that my app can be activated whenever any trigger run.
I tried to edit the auto-created ScaledObject created by this controller and managed to trigger the app. However, it does not work as expected in several cases. For example:
- CooldownPeriod is always 300s no matter how much I set
- App does not get scaled down occasionally
- Sometimes, app is stucked in a scaled up then terminated instantly loop

What is the idiomatic way to do this or this use case is not yet supported and is supposed to give undefined behaviors?

**Comment by arschles** [comment]
@tidunguyen the HTTP Addon just creates a `ScaledObject` behind the scenes for your `Deployment`. You should probably not touch that one (although it is possible to change the cooldown period after it is created by the http addon operator), but you could create additional `ScaledObject`s. The only thing to watch out for is if two or more scaling operations compete, which you likely don't want. I would recommend making sure that, if you do go this route, you make sure that two scalers do not attempt to scale your `Deployment` at the same time

**Reply by tomkerkhove** [reply]
It's interesting discussion though because we always recommend to only have 1 ScaledObject per workload to avoid flapping between both of them.

Maybe we should consider allowing "additional triggers"?

**Reply by tomkerkhove** [reply]
Curious about what those other triggers in your scenario would be though @tidunguyen?

**Reply by tdnguyen6** [reply]
I added `metrics-api` triggers to the generated scaledobj and get those behaviors.

**Reply by AGovorukha** [reply]
> I added `metrics-api` triggers to the generated scaledobj and get those behaviors.

but how to automate it using Helm? It is a strange solution to edit ScaledObject every time.
Say, I have a template for HTTPScaledObject that should be rendered if I have targetPendingRequests not null in the values file and at the same time I would like to scale based on CPU usage. I can have two templates for HTTPScaledObject and ScaledObject. But for sure it is better to have one and be sure that KEDA scales my app correctly and these two triggers will not compete with each other.

**Comment by kjfly** [comment]
Facing similar situation. I need to add a trigger based on messages in a queue. It is possible that both the http and message based trigger to happen at the same time. Is there any recommendations on how to either use additional triggers on http scaledobject or have multiple scaled objects that do not interfere with each other?

**Reply by kjfly** [reply]
This is preventing us from using http-add-on trigger since admission hook does not allow having multiple scaled objects manage the same deployment. Any suggestions on how to add more triggers using Helm will be very helpful!

**Comment by gewlar** [comment]
In our scenario we would use the http-add-on to trigger scale up. Processing requests take a long time, so is solved with polling directly to the respective pod instead.  Is there a way to keep pods alive until their cpu usage drops down?

**Comment by leblancmeneses** [comment]
I am trying to save on costs when no one uses the preview environments.
I want to turn off cronjobs ```kubectl patch cronjobs <job-name> -p '{"spec" : {"suspend" : true }}'``` when HTTPScaledObject triggers a scale to zero on our API deployment.


Can anything support suspending the cronjobs when API is at zero or mirroring scale down to another deployment?


Possibly something like this:

```
    kind: WatchScaledObject
    watchTargetRef:
        - name: {{ include "xyz.fullname" . }}-api
          kind: Deployment
          apiVersion: apps/v1
    suspendTargetRef:
        - name: {{ include "xyz.fullname" . }}-cron-every-15-min
          kind: CronJob
          apiVersion: batch/v1
        - name: {{ include "xyz.fullname" . }}-cron-every-1-hour
          kind: CronJob
          apiVersion: batch/v1
    mirrorScaleTargetRef:
        - name: {{ include "xyz.fullname" . }}-mysql
          kind: Deployment
          apiVersion: apps/v1
```
