### DISCUSSION TITLE
How long before the deployment scales back to zero replica as there are zero incoming request

### DISCUSSION THREAD

**Discussion by jaiprasad266** [kedacore/http-add-on#507] [Q&A]
The httpscaledobject configuration is like below:

The first two request to ```curl -H "Host: myhost.com" 192.168.5.15/query``` returned ```error on backend (dial tcp 10.43.149.72:8080: connect: connection refused)``` ,  and third request was successful and the replica got scaled up to 1. 

With zero incoming request , it took more than 8 minutes to scale back to 0 . 
I was expecting it scale down bit faster. 

```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ include "quarkus-rest-server.fullname" . }}
spec:
    host: myhost.com
    targetPendingRequests: 100
    scaleTargetRef:
        deployment: quarkus-rest-server
        service: quarkus-rest-server
        port: 8080
    replicas:
        min: 0
        max: 5    
```
