### DISCUSSION TITLE
Autoscale https upstream service

### DISCUSSION THREAD

**Discussion by cary205** [kedacore/http-add-on#735] [Q&A]
Hello,

I have deployed a deployment which I want to autoscale.
The deployment exposes port with https.
Is http-add-on supports https upstream service?

Thanks

**Comment by tomkerkhove** [comment]
Yes, it should. Did you encounter issues?

**Comment by nkuzman** [comment]
Hi @tomkerkhove ,

I'm not sure if I have the same issue as @cary205 there, but I also encountered a problem with HTTPS port.

So, an application exposes HTTPS port only and is exposed to public via ingress (nginx) which has SSL passthrough enabled (certificate is served by microservice itself, not by ingress).

HTTP add-on is installed in a separate namespace from application itself, so I use an ExternalName service to route requests to interceptor.
The problem is that as soon as I switch ingress to point to ExternalName service instead of application's service, HTTPS requests start to fail, and application can be accessed only via HTTP, which triggers scaler, but requests obviously fail with bad gateway error.

Ingress setup:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: myapp
spec:
  ingressClassName: nginx
  rules:
  - host: myhost.com
    http:
      paths:
      - backend:
          service:
            name: externalname-service
            port:
              number: 8080
        path: /
        pathType: Prefix
```

ExternalName service:
```
apiVersion: v1
kind: Service
metadata:
  name: externalname-service
spec:
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  type: ExternalName
```

Application service:
```
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
```

HTTPScaledObject:
```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: myapp-scaler
spec:
    hosts:
        - "myhost.com"
    targetPendingRequests: 1
    scaleTargetRef:
        deployment: myapp
        service: myapp-service
        port: 8443
```
Add-on was installed using default settings (interceptor proxy listens on 8080).

It there a misconfiguration somewhere or am I missing some additional setup which is required for this scenario?
Please let me know if you need some additional info.

Thank you.

**Comment by gshhong** [comment]
I also encountered the same problem.
I am not sure if the latest version 0.8.0 has solved this problem.

**Comment by nkuzman** [comment]
Hi @linkvt,

since the discussion was closed as resolved, could you please add a comment on how/when it was resolved?
Thank you.

**Reply by linkvt** [reply]
Hi @nkuzman ,

sure, I'm mostly cleaning up old discussions but didn't notice that this seems still relevant.

Not completely sure if this matches your requirements, but I was able to setup my environment so that I could send HTTP and HTTPS requests to my ingress controller through the interceptor to the backend service only serving HTTPS.

The interceptor is currently only able to send HTTPS requests to services, when the requests also enter the interceptor through its HTTPS port (8443).

This means I had to do the following:
1. Create a certificate for the interceptor, e.g. using cert-manager
2. Configure my HTTP Addon deployment to use it:
    - ```yml
      interceptor:
        replicas:
          min: 1
        extraEnvs:
          KEDA_HTTP_PROXY_TLS_SKIP_VERIFY: "true" # I chose the lazy way for this test
        tls:
          enabled: true
          cert_secret: keda-interceptor-tls-cert
      ```
3. Configure my ingress controller, traefik in this case
	- Always send requests to `https://keda-add-ons-http-interceptor-proxy.keda:443`
	- Ignore TLS verification errors again (lazy implementation for this test)
	- Accept requests on HTTP and HTTPS entrypoints

<details>
<summary>Resource Dump</summary>

```yaml
# sslip domains need to be changed in all places to match your environment
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-traefik-tls
  labels:
    app: whoami-traefik-tls
spec:
  secretName: whoami-traefik-tls-cert
  issuerRef:
    name: ingress-issuer
    kind: ClusterIssuer
  commonName: whoami-traefik-tls.10.89.0.219.sslip.io
  dnsNames:
    - whoami-traefik-tls.10.89.0.219.sslip.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-traefik-tls
  labels:
    app: whoami-traefik-tls
spec:
  replicas: 0
  selector:
    matchLabels:
      app: whoami-traefik-tls
  template:
    metadata:
      labels:
        app: whoami-traefik-tls
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest
          args:
            - --cert=/certs/tls.crt
            - --key=/certs/tls.key
          ports:
            - name: https
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: tls-cert
              mountPath: /certs
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTPS
            initialDelaySeconds: 1
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: tls-cert
          secret:
            secretName: whoami-traefik-tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-traefik-tls
  labels:
    app: whoami-traefik-tls
spec:
  type: ClusterIP
  selector:
    app: whoami-traefik-tls
  ports:
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: whoami-traefik-tls
  labels:
    app: whoami-traefik-tls
spec:
  hosts:
    - whoami-traefik-tls.10.89.0.219.sslip.io
  scaleTargetRef:
    name: whoami-traefik-tls
    kind: Deployment
    apiVersion: apps/v1
    service: whoami-traefik-tls
    port: 443
  scalingMetric:
    concurrency:
      targetValue: 10
  replicas:
    min: 0
    max: 10
---
# ServersTransport for TLS backend (interceptor) - must be in keda namespace
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: interceptor-transport
  namespace: keda
  labels:
    app: whoami-traefik-tls
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-traefik-tls-http
  labels:
    app: whoami-traefik-tls
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami-traefik-tls.10.89.0.219.sslip.io`)
      kind: Rule
      services:
        - name: keda-add-ons-http-interceptor-proxy
          namespace: keda
          port: 8443
          scheme: https
          passHostHeader: true
          serversTransport: interceptor-transport
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-traefik-tls
  labels:
    app: whoami-traefik-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami-traefik-tls.10.89.0.219.sslip.io`)
      kind: Rule
      services:
        - name: keda-add-ons-http-interceptor-proxy
          namespace: keda
          port: 8443
          scheme: https
          passHostHeader: true
          serversTransport: interceptor-transport
  tls:
    secretName: whoami-traefik-tls-cert

```

</details>


The current implementation seems a bit restrictive to be honest so not sure if it solves your requirements as you mentioned TLS passthrough. I don't think that we can support TLS passthrough as this is more of a layer 4 concept while the HTTP addon is currently implemented on layer 7 where it terminates requests to route them based on their path and headers.

We are currently working on the HTTP Addon to make it production ready which is why we are looking through the discussions and also issues (where some have been autoclosed).
We can further refine your requirements here but feature requests should end up in a dedicated issue  🙂
