### DISCUSSION TITLE
Path/Route based Scaling feature example

### DISCUSSION THREAD

**Discussion by zetfactor** [kedacore/http-add-on#754] [Q&A]
Hi all, 

As per 0.5.0 Release notes [here](https://github.com/kedacore/http-add-on/releases/tag/v0.5.0)

**NEW** Routing: Support path-based routing 
 
I already read multiple discussions here regarding this feature. However I was not able to implement it.

If someone can clarify, or provide me with any tips I would be grateful.

**Environment:**
Minikube v1.31.2
KEDA  v2.11.2
Keda-add-ons 0.5.0

`kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: nginx-http-scaledobject
spec:
    host: myhost.com
    path: /foo/bar
    targetPendingRequests: 1
    scaleTargetRef:
        deployment: nginx
        service: nginx
        port: 80
    replicas:
        min: 0
        max: 3`

I tried both "path" & "pathPrefix" , howeverI keep getting these errors:

> Error from server (BadRequest): error when creating "http-scaleObject.yml": HTTPScaledObject in version "v1alpha1" cannot be handled as a HTTPScaledObject: strict decoding error: unknown field "spec.path"

> Error from server (BadRequest): error when creating "http-scaleObject.yml": HTTPScaledObject in version "v1alpha1" cannot be handled as a HTTPScaledObject: strict decoding error: unknown field "spec.pathPrefix"

**Comment by ianuragsingh** [comment]
I tried v0.6.0, still getting the same issue.

**Reply by nkuzman** [reply]
https://github.com/kedacore/http-add-on/blob/2fa0be3f25b5ee9e1612e09a96d6a6b7258f583b/operator/controllers/http/scaled_object.go#L44

Had the same issue, found out that implementation expects "spec.pathPrefixes" list.
I managed to run it with this setup:

```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: demo
spec:
    hosts:
        - "myhost.com"
    pathPrefixes:
        - /custom/path
    scaleTargetRef:
        deployment: demo
        service: demo
        port: 8080
```

**Reply by machecazzon** [reply]
I have the same issue on 0.6.0
```
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
   name: podinfo
spec:
  # host: example.com
  hosts:
  - example.com
  pathPrefixes:
  - /delay/
  targetPendingRequests: 2
  scaleTargetRef:
    deployment: podinfo
    service: podinfo
    port: 80
  replicas:
    min: 0
    max: 5
```

attempted other combinations but nothing works for me other than `/`
I am basically using podinfo as workload

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898

---
apiVersion: v1
kind: Service
metadata:
 name: podinfo
spec:
 ports:
  - port: 80
    targetPort: 9898
 selector:
   app: podinfo
```


```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: podinfo-load-generator
spec:
  template:
    spec:
      containers:
      - name: apache-ab
        image: ghcr.io/kedacore/tests-apache-ab
        imagePullPolicy: Always
        args:
          - "-n"
          - "500"
          - "-c"
          - "1"
          - "-H"
          - "Host: example.com"
          - "http://keda-http-add-on-interceptor-proxy.keda:8080/delay/1"
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
  activeDeadlineSeconds: 600
  backoffLimit: 5
```

```
│ {"level":"error","ts":1702764504.9121535,"logger":"LoggingMiddleware.RoutingMiddleware.CountingMiddleware.UpstreamHandler.StaticHandler","caller":"handler/static.go:36","msg":"Bad Gateway","routingKey":"//example.com/delay/1/","namespacedNam │
│ {"level":"info","ts":1702764504.9124231,"logger":"LoggingMiddleware","caller":"middleware/logging.go:73","msg":"10.42.0.100:42722 - - [16/Dec/2023:22:08:24 +0000] \"GET /delay/1 HTTP/1.0\" 502 11 \"\" \"ApacheBench/2.3\""}                    │
│ 
```


curl to podinfo service works just fine. something must might be going on the interceptor-proxy  

```
/ # curl podinfo.test
{
  "hostname": "podinfo-fc57fb7d8-r74ff",
  "version": "6.5.3",
  "revision": "d9bc6301e9b614cbe24e190396bc574d51a2427d",
  "color": "#34577c",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from podinfo v6.5.3",
  "goos": "linux",
  "goarch": "arm64",
  "runtime": "go1.21.3",
  "num_goroutine": "9",
  "num_cpu": "10"
/ # curl podinfo.test/delay/2
{
  "delay": 2
}/ #
```
