### DISCUSSION TITLE
Scaling of Microservice not working with http-add-on with internal http requests

### DISCUSSION THREAD

**Discussion by Sathya-omnius** [kedacore/http-add-on#776] [Q&A]
Hi Team,

we have Microservice deployed in kubernetes, would like to scale this Microservice. This Microservice is called by other Micro services internally with in the application for all the operations, there are no external http request ,all the http requests are internal from the other micro services, could you please help us how to scale this Microservice base on internal http requests.

**Comment by michel-numan** [comment]
@Sathya-omnius 

You need to create a separate service for the app, and point the service to a ExternalName to your ingress controller. Then create an ingress object (or equivalent) which captures the name of the service, and routes to the keda-proxy service (Which is also an ExternalName service to the keda interceptor)

**Comment by EinavDanielDX** [comment]
I encountered a similar use case. 
I found @michel-numan's suggestion a bit too complex to configure. 
In the end, I created a single ExternalName service pointing to the interceptor. Calling this endpoint with the appropriate Host header solved the issue for me

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-interceptor-proxy-bridge
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: my-service-httpscaler
  annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: "false"
spec:
  hosts:
  - any-domain-name.cluster.internal
  pathPrefixes:
  - "/api/v1/hello"
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: my-deployment
    service: my-service
    port: 80
  replicas:
    min: 0
    max: 3
  scaledownPeriod: 60
  scalingMetric: # requestRate and concurrency are mutually exclusive
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m
```

Then, executed curl command from an internal pod `http://my-interceptor-proxy-bridge:8080/api/v1/hello --header 'Host: any-domain-name.cluster.internal`

Note: I used http addon version **0.8.0**
