### DISCUSSION TITLE
Question about spec.replicas.min and spec.replicas.max

### DISCUSSION THREAD

**Discussion by jesumyip** [kedacore/http-add-on#962] [General] [answered]
What exactly do these 2 parameters control?

All the blogs and articles I have read do not explain it very well (or it's my complete lack of understanding that's preventing me from moving forward. :) )

```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: test-test
spec:
    host: "mytest.test.com"
    targetPendingRequests: 10
    scaledownPeriod: 300
    scaleTargetRef:
        deployment: myapp
        service: myservice
        port: 8080
    replicas:
        min: 0
        max: 10
```
Assuming I have 11 pending requests in queue (assuming zero pods initially and I fire off `curl` 11 times), does this mean this add-on will spin up 1 pod in my deployment? If so, then when does the number of pods being spun up go from 1 to 2, 2 to 3, 3 to 4, until 9 to 10? And will it at any time jump by a factor larger than 1 i.e. 1 to 3 replicas (i.e. jump by a factor of 2 instead of 1)?
