### DISCUSSION TITLE
Can I install keda + http addon on namespace "A" and use it to scale applications deployed in namespaces "B" and "C"?

### DISCUSSION THREAD

**Discussion by MewanthaB** [kedacore/http-add-on#990] [Q&A] [answered]
I've been trying unsuccessfully to do this. I have installed keda + http addon on namespace "A", and want to use it to scale applications on 2 other namespaces based on number of requests. However, I'm not sure this is possible based on the the [documentation](https://keda.sh/blog/2021-06-24-announcing-http-add-on/#install-an-httpscaledobject) 

> The HTTPScaledObject CRD instructs the operator to install and configure the interceptor and scaler for a specified Deployment. For this to work, you’ll need to have a Deployment running in the **same $NAMESPACE**

But this [other answer here](https://github.com/kedacore/http-add-on/discussions/566#discussioncomment-4683189) says it is possible. So is the only way the addon will work be if I move both other applications to namespace A? Or can we do multiple namespaces? Just want to confirm since I have been unsuccessful so far and the doc is a little unclear. Thanks!

**Comment by shreya0910** [comment]
I am trying to setup in similar way keda + httpadd on is in keda namespace & application + ingress is in app ns. Created Ingress, NGINX Ingress Controller and ExternalName Service setup but so far its not working as expected
interceptor is not reachable from nginx

**Reply by SevginGalibov** [reply]
@shreya0910 I am having the same problem. Did you solve it?

**Reply by rd-zahari-aleksiev** [reply]
Maybe your ingress should reach the keda-add-ons-http-interceptor-proxy not the http interceptors directly ? like "http://keda-add-ons-http-interceptor-proxy.keda:8080"

**Comment by rd-zahari-aleksiev** [comment, marked as answer]
It is working, I have KEDA+HTTP add on in keda namespace and I'm scaling services in many different namespaces, (HTTP)ScaledObjects must be alongside respective namespaces of the services I'm scaling. In other words not in the keda namespace.

**Reply by SevginGalibov** [reply]
> It is working, I have KEDA+HTTP add on in keda namespace and I'm scaling services in many different namespaces, (HTTP)ScaledObjects must be alongside respective namespaces of the services I'm scaling. In other words not in the keda namespace.

So let me summarize the topic.

http add ons and keda operator are installed in the "keda" namespace. The service list is as follows;

```
keda-add-ons-http-controller-manager-metrics-service   ClusterIP   x.x.x.x  	<none>        8443/TCP           2d8h
keda-add-ons-http-external-scaler                      ClusterIP   x.x.x.x      <none>        9090/TCP           2d8h
keda-add-ons-http-interceptor-admin                    ClusterIP   x.x.x.x     	<none>        9090/TCP           2d8h
keda-add-ons-http-interceptor-proxy                    ClusterIP   x.x.x.x    	<none>        8080/TCP           2d8h
keda-admission-webhooks                                ClusterIP   x.x.x.x    	<none>        443/TCP            2d9h
keda-interceptor-proxy                                 ClusterIP   x.x.x.x   	<none>        8080/TCP           2d8h
keda-operator                                          ClusterIP   x.x.x.x  	<none>        9666/TCP           2d9h
keda-operator-metrics-apiserver
```


I have an external API service in the "test" namespace and an externalname service for the keda interceptor.
                                                
```
api-service                   ClusterIP      x.x.x.x  <none>                                                       		  80/TCP    2d8h
keda-interceptor-proxy-test   ExternalName   <none>          keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local   80/TCP    2d8h
```



The content of my external service in the "test" namespace is as follows;

```
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
```


I also have an nginx ingress for my api-service in the "test" namespace;

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  generation: 6
  name: api-ingress
  namespace: test
spec:
  ingressClassName: nginx
  rules:
  - host: www.api.com
    http:
      paths:
      - backend:
          service:
            name: keda-interceptor-proxy-test
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: x.x.x.x

```

keda-add-ons-http-interceptor logs;

```
2025-02-09T22:21:04Z	ERROR	LoggingMiddleware.RoutingMiddleware.StaticHandler	Not Found	{"routingKey": "//www.api.com/weatherforecast/", "namespacedNameError": "PANIC=value method k8s.io/apimachinery/pkg/types.NamespacedName.MarshalLog called using nil *NamespacedName pointer", "stream": "<nil>"}
github.com/kedacore/http-add-on/interceptor/handler.(*Static).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/handler/static.go:36
github.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/routing.go:54
github.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/logging.go:42
github.com/kedacore/http-add-on/interceptor/middleware.(*Metrics).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/metrics.go:24
net/http.serverHandler.ServeHTTP
	net/http/server.go:3210
net/http.(*conn).serve
	net/http/server.go:2092
```
When I send the request I get a not found warning on a black page.

What is the problem in this case?
