### ISSUE TITLE
namespacedNameError on Proxy when attempting to submit a cURL call to it

### ISSUE THREAD

**Issue by Varun-Mehrotra** [kedacore/http-add-on#1041]
### Report

The Keda http proxy is unable to find hosts and returns NamespacedName is nil error

### Expected Behavior

When the proxy is hit with an appropriate host it should be able to serve traffic without an error 

### Actual Behavior

When I portforward the http-add-on proxy and hit it with a cURL call, it returns `Not Found` and the following can be seen on the `keda-add-ons-http-interceptor-proxy` logs: 

```
RROR    LoggingMiddleware.RoutingMiddleware.StaticHandler    Not Found    {"routingKey": "//myhost.com/", "namespacedNameError": "PANIC=value method k8s.io/apimachinery/pkg/types.NamespacedName.MarshalLog called using nil *NamespacedName pointer", "stream": "<nil>"}
github.com/kedacore/http-add-on/interceptor/handler.(*Static).ServeHTTP
    github.com/kedacore/http-add-on/interceptor/handler/static.go:36
github.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP
    github.com/kedacore/http-add-on/interceptor/middleware/routing.go:49
github.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP
    github.com/kedacore/http-add-on/interceptor/middleware/logging.go:42
github.com/kedacore/http-add-on/interceptor/middleware.(*Metrics).ServeHTTP
    github.com/kedacore/http-add-on/interceptor/middleware/metrics.go:24
net/http.serverHandler.ServeHTTP
    net/http/server.go:3137
net/http.(*conn).serve
    net/http/server.go:2039
```

### Steps to Reproduce the Problem

1. Attempt to deploy the example helm chart
2. Port forward the proxy to 8080:8080 as the walkthrough suggests with `kubectl port-forward svc/keda-add-ons-http-interceptor-proxy -n keda 8080:8080` 
3. Run the following cURL call: `curl -H "Host:myhost.com" 127.0.0.1:8080`

### Logs from KEDA HTTP operator

N/A, no relevant HTTP operator logs

### HTTP Add-on Version

0.8.0

### Kubernetes Version

1.28

### Platform

Amazon Web Services

### Anything else?

Keda is installed in the `keda` namespace along with the http-add-on: 
<img width="1294" alt="image" src="https://github.com/kedacore/http-add-on/assets/69325697/3deab6ad-3ce1-4236-b952-9d698f72cee8">

**Comment by Varun-Mehrotra** [comment]
Nevermind, this wasn't the case. Not sure what the specific issues was here but I've got a good feeling I just made a spelling mistake somewhere and when I re-applied things they fixed themselves.  Regardless I spent some time going down a rabbit hole. Couple of learnings for anybody who might stumble on this: 

1. DNS may have trouble resolving for the externalName service, always try out the FQDN (i.e. `keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local`) before trying much else. 
2. The ALB Ingress Controller does not play nice with the externalName service as of now either, [but there is an open PR as of writing this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3571). To get around it, I unfortunately just have to run keda and the http add on in each of my namespaces.

**Comment by SevginGalibov** [comment]
Same problem nginx ingress;

So let me summarize the topic.

http add ons and keda operator are installed in the "keda" namespace. The service list is as follows;

```
keda-add-ons-http-controller-manager-metrics-service   ClusterIP   x.x.x.x  	<none>        8443/TCP           2d8h
keda-add-ons-http-external-scaler                      ClusterIP   x.x.x.x      <none>        9090/TCP           2d8h
keda-add-ons-http-interceptor-admin                    ClusterIP   x.x.x.x     	<none>        9090/TCP           2d8h
keda-add-ons-http-interceptor-proxy                    ClusterIP   x.x.x.x    	<none>        8080/TCP           2d8h
keda-admission-webhooks                                ClusterIP   x.x.x.x    	<none>        443/TCP            2d9h
keda-interceptor-proxy                                 ClusterIP   x.x.x.x   	<none>        8080/TCP           2d8h
keda-operator                                          ClusterIP   x.x.x.x  	<none>        9666/TCP           2d9h
keda-operator-metrics-apiserver
```


I have an external API service in the "test" namespace and an externalname service for the keda interceptor.
                                                
```
api-service                   ClusterIP      x.x.x.x  <none>                                                       		  80/TCP    2d8h
keda-interceptor-proxy-test   ExternalName   <none>          keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local   80/TCP    2d8h
```



The content of my external service in the "test" namespace is as follows;

```
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
```


I also have an nginx ingress for my api-service in the "test" namespace;

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  generation: 6
  name: api-ingress
  namespace: test
spec:
  ingressClassName: nginx
  rules:
  - host: www.api.com
    http:
      paths:
      - backend:
          service:
            name: keda-interceptor-proxy-test
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: x.x.x.x

```

keda-add-ons-http-interceptor logs;

```
2025-02-09T22:21:04Z	ERROR	LoggingMiddleware.RoutingMiddleware.StaticHandler	Not Found	{"routingKey": "//www.api.com/weatherforecast/", "namespacedNameError": "PANIC=value method k8s.io/apimachinery/pkg/types.NamespacedName.MarshalLog called using nil *NamespacedName pointer", "stream": "<nil>"}
github.com/kedacore/http-add-on/interceptor/handler.(*Static).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/handler/static.go:36
github.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/routing.go:54
github.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/logging.go:42
github.com/kedacore/http-add-on/interceptor/middleware.(*Metrics).ServeHTTP
	github.com/kedacore/http-add-on/interceptor/middleware/metrics.go:24
net/http.serverHandler.ServeHTTP
	net/http/server.go:3210
net/http.(*conn).serve
	net/http/server.go:2092
```
When I send the request I get a not found warning on a black page.

What is the problem in this case?
