### ISSUE TITLE
Deprecate `spec.scaleTargetRef.deployment`

### ISSUE THREAD

**Issue by zroubalik** [kedacore/http-add-on#1061]
### Proposal

Let's deprecate this field to be able to support more types, not just Deployments. The same way it is done for KEDA.

```yaml
kind: HTTPScaledObject
...
spec:
...
    scaleTargetRef:
        deployment: xkcd
        service: xkcd
        port: 8080
```

->

```yaml
kind: HTTPScaledObject
...
spec:
...
    scaleTargetRef:
        name: xkcd
        kind: Deployment
        apiVersion: apps/v1
        service: xkcd
        port: 8080
```

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by Leonardo-Ferreira** [comment]
Does version 0.8 of the http interceptor accepts this?

**Comment by zroubalik** [comment]
v10 doesn't have this field, let's use the new one:

https://github.com/kedacore/http-add-on/blob/6fa0b98608ba73c165f9eee5c99435d5cae3b7b4/operator/apis/http/v1alpha1/httpscaledobject_types.go#L24-L37

**Comment by Leonardo-Ferreira** [comment]
yes I got that part, what im asking is: does v8 supports the contract that is mandatory in v10? aka, does V8 supports
```
kind: HTTPScaledObject
...
spec:
...
    scaleTargetRef:
        name: xkcd
        kind: Deployment
        apiVersion: apps/v1
        service: xkcd
        port: 8080
```
???
