### ISSUE TITLE
HTTP Add-on not working with other scalers or when scaled object is created separately

### ISSUE THREAD

**Issue by utsav-simplismart** [kedacore/http-add-on#1083]
### Report

Http Add-on standalone is working fine. But when creating a separate scaledobject with httpscaledobject defined as external push trigger, it is not working. 

### Expected Behavior

It should scale even if the scaledobject is created separately with an external push trigger to the HTTPscaledobject. 

### Actual Behavior

When using httpscaledobject with below annotation and with minimum replica as 0, it is working fine. It is scaling from 0 to 1 when new request comes in.
``` yaml
annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: 'false'
```

But when creating httpscaledobject with annotation set to true and with minimum replica as 0, it is not working even after creating a separate ScaledObject.

``` yaml
annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: 'true'
```

The trigger in scaledobject looks like this:

``` yaml
triggers:
    - metadata:
        httpScaledObject: cognizant-keda-http-scaledobject # name of HTTPScaledObject
        scalerAddress: 'keda-add-ons-http-external-scaler.keda:9090'
      type: external-push
```

### Steps to Reproduce the Problem

1. Create a HTTPScaledObject with below annotation with minimum replica as 0:
  
``` yaml
annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: 'true'
```
2. Create a separate Scaledobject with trigger as below with minimum replica as 0:
 ``` yaml
triggers:
    - metadata:
        httpScaledObject: cognizant-keda-http-scaledobject # name of HTTPScaledObject
        scalerAddress: 'keda-add-ons-http-external-scaler.keda:9090'
      type: external-push
```
3. Send a request to target deployment/service.

### Logs from KEDA HTTP operator

```
example
```

### HTTP Add-on Version

0.8.0

### Kubernetes Version

None

### Platform

Amazon Web Services
