### ISSUE TITLE
Active field from kubectl get httpscaledobject is always empty

### ISSUE THREAD

**Issue by josegonzalez** [kedacore/http-add-on#1211]
### Report

The "Active" field appears to be queried incorrectly, causing it to always be empty.

https://github.com/kedacore/http-add-on/blob/45f645f19e6e76ede4b61a5278665ac92d1e576e/config/crd/bases/http.keda.sh_httpscaledobjects.yaml#L35

```
 .status.conditions[?(@.type=="HTTPScaledObjectIsReady")].status
```

Is the query, but the `type` is never that value. Instead, that is the `reason`:

```yaml
status:
  conditions:
  - message: Identified HTTPScaledObject creation signal
    reason: PendingCreation
    status: Unknown
    timestamp: "2024-12-11T00:59:45Z"
    type: Ready
  - message: Finished object creation
    reason: HTTPScaledObjectIsReady
    status: "True"
    timestamp: "2024-12-11T00:59:45Z"
    type: Ready
```

### Expected Behavior

Either a value of "True" or "False"

### Actual Behavior

Empty value

### Steps to Reproduce the Problem

1. Create any HTTPScaledObject
2. Call `kubectl get HTTPScaledObject`
3. See that the value under the `Active` column is empty.

### Logs from KEDA HTTP operator

```
n/a
```

### HTTP Add-on Version

0.8.0

### Kubernetes Version

1.30

### Platform

Other
