### ISSUE TITLE
With multiple triggers (CPU and HTTP) and minReplicaCount of 0, KEDA erroneously scales to 0.

### ISSUE THREAD

**Issue by mengland-noaa** [kedacore/http-add-on#1262]
### Report

With CPU and the http-external-scaler together as triggers in the same scaled object, behavior is not as expected.
With CPU under heavy load it scales up successfully, but KEDA subsequently intervenes and scales to 0 ignoring CPU.

### Expected Behavior

Under heavy CPU load even with no http requests KEDA should not scale down to 0.

### Actual Behavior

The HTTP add on appears to be overriding the CPU scaler.

### Steps to Reproduce the Problem

1. Create an nginx or other deployment paired with a CPU load test side car or init container. The memory scaler behaves similarly.
2. Create scaled objects and watch as it initially scales up then scales back down to 0:

kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: my-scaled-object
  annotations:
      httpscaledobject.keda.sh/skip-scaledobject-creation: "true"
spec:
  hosts:
  - "myhost"
  scaledownPeriod: 10
  scaleTargetRef:
      name: my-web-server-deployment
      service: my-web-server-service
      port: 80
  replicas:
      min: 0
      max: 5
  targetPendingRequests: 1
---    
kind: ScaledObject
apiVersion: keda.sh/v1alpha1
metadata:
  name: my-scaled-object
spec:
  cooldownPeriod: 15  # Wait 15s before scaling down
  minReplicaCount: 0  # Scale down to zero when idle
  maxReplicaCount: 5  # Scale up if needed
  pollingInterval: 20  # Check every 20s
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-server-deployment  # Target Deployment
  triggers:
    - type: cpu
      metadata:
        type: AverageValue
        value: "50"  # Scale when CPU utilization exceeds 50% per pod
    - type: external-push
      metadata:
        httpScaledObject: my-scaled-object
        hosts: "myhost"
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090

### HTTP Add-on Version

0.10.0

### Kubernetes Version

None

### Platform

Any

**Comment by rd-zahari-aleksiev** [comment]
I think is the same issue -> https://github.com/kedacore/http-add-on/issues/1147

**Comment by rd-zahari-aleksiev** [comment]
@JorTurFer , what do you think, is my analysis makes sense? :-)

**Comment by leorniduv** [comment]
Hi, just wanted to +1 this issue, I'm having the same difficulties making a cron trigger work with a http scaler

```
    - kind: HTTPScaledObject
      apiVersion: http.keda.sh/v1alpha1
      metadata:
        name: my-app
        annotations:
          httpscaledobject.keda.sh/skip-scaledobject-creation: "true"
      spec:
        hosts:
          - my-app.hello.world
        scaleTargetRef:
          name: my-app
          kind: Deployment
          apiVersion: apps/v1
          service: my-app
          port: 11434
        replicas:
          min: 0
          max: 3
        scaledownPeriod: 30
        scalingMetric:
          concurrency:
            targetValue: 10
    - kind: ScaledObject
      apiVersion: keda.sh/v1alpha1
      metadata:
        name: my-app
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: my-app
        pollingInterval: 10
        cooldownPeriod: 30
        initialCooldownPeriod: 0
        minReplicaCount: 0
        maxReplicaCount: 3
        triggers:
          - type: cron
            metadata:
              timezone: Europe/Paris
              start: 0 9 * * 1-5
              end: 0 19 * * 1-5
              desiredReplicas: "1"
          - type: external-push
            metadata:
              httpScaledObject: my-app
              scalerAddress: keda-add-ons-http-external-scaler.keda:9090
```

A pod spawns and then is immediately shut down

**Comment by leorniduv** [comment]
If anyone needs this I've found a **very stupid** way of making this setup work. You basically create another cron ScaledObject that kills the Http Add-on at the same time 🤦 I tested it and it seems to be doing the job: what needs to be killed outside the cron gets killed, and during the cron, my app is up and scaled based on http traffic.

```yaml
    - kind: HTTPScaledObject
      apiVersion: http.keda.sh/v1alpha1
      metadata:
        name: my-app-http
      spec:
        hosts:
          - bla.bla.foo
        scaleTargetRef:
          name: my-app
          kind: Deployment
          apiVersion: apps/v1
          service: my-app
          port: 3601
        replicas:
          min: 1 # changed from 0 to 1
          max: 3
        scaledownPeriod: 30
        scalingMetric:
          concurrency:
            targetValue: 10
    - kind: ScaledObject
      apiVersion: keda.sh/v1alpha1
      metadata:
        name: my-app-cron
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: my-app
        pollingInterval: 10
        cooldownPeriod: 30
        initialCooldownPeriod: 0
        minReplicaCount: 0
        maxReplicaCount: 3
        triggers:
          - type: cron
            metadata:
              timezone: Europe/Paris
              start: 0 9 * * 1-5
              end: 0 19 * * 1-5
              desiredReplicas: "1"
  # New ScaledObject that kills the external-scaler on the same cron interval
    - kind: ScaledObject
      apiVersion: keda.sh/v1alpha1
      metadata:
        name: keda-external-scaler-cron
        namespace: keda
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: keda-add-ons-http-external-scaler
        pollingInterval: 10
        cooldownPeriod: 30
        initialCooldownPeriod: 0
        minReplicaCount: 0
        maxReplicaCount: 3
        triggers:
          - type: cron
            metadata:
              timezone: Europe/Paris
              start: 0 9 * * 1-5
              end: 0 19 * * 1-5
              desiredReplicas: "1"
```

Again, this is **very stupid** and only works if you are using the Http add-on for a specific app (should probably deploy in namespace-mode and not cluster-wide now that I think of it ; to be a bit cleaner). + I'm not familiar with Go so I don't think I can pull off a PR to fix the real issue, this is just a hack to get it working :/
