### ISSUE TITLE
Way to modify annotations and labels for created resources

### ISSUE THREAD

**Issue by khaosdoctor** [kedacore/http-add-on#36]
The operator creates all the resources with default labels and specs, it'd be good to add a section to the CRD spec that allowed users to add their own labels and annotations.

A simple use case would be a user who wants to use the HTTP Application Routing add-on from AKS, it needs the annotation in the ingress resource so it can update the DNS records.

**Comment by arschles** [comment]
cc/ @khaosdoctor

**Comment by khaosdoctor** [comment]
On it after #42

**Comment by khaosdoctor** [comment]
#42 is finished, on it

**Comment by khaosdoctor** [comment]
I'm thinking on changing a bit the API, here's the current one:

```yaml
spec:
  appName:
  image:
  port:
  pollingInterval:
```

My suggestion:

```yaml
spec:
  app:
    image:
    name:
    port:
    labels:
    annotations:
  ingress:
    labels:
    annotations:
    host:
    enabled:
  service:
    labels:
    annotations:
    port:
  pollingInterval:
```

**Comment by arschles** [comment]
@khaosdoctor I'd like to keep the spec simple for now, so how about something that will add annotations to all created resources:

```yaml
spec:
  appName:
  image:
  port:
  pollingInterval:
  annotations: # the fields in here will be put as annotations on all created resources
```

if there's a use case for custom annotations on some resources but not others, I'm open to breaking out the resources as you suggested. WDYT?
