### ISSUE TITLE
Getting "unknown field "targetPendingRequests"" while deploying HTTP Scaled Object

### ISSUE THREAD

**Issue by Giridhar23689** [kedacore/http-add-on#368]
### Report

While deploying an HTTP scaled object, I received the below error:

 _error validating data: ValidationError(HTTPScaledObject.spec.scaleTargetRef): unknown field "targetPendingRequests" in sh.keda.http.v1alpha1.HTTPScaledObject.spec.scaleTargetRef; if you choose to ignore these errors, turn validation off with --validate=false_

### Expected Behavior

The HTTP scaled object should be deployed,

### Actual Behavior

I am getting the below validation error:

 _error validating data: ValidationError(HTTPScaledObject.spec.scaleTargetRef): unknown field "targetPendingRequests" in sh.keda.http.v1alpha1.HTTPScaledObject.spec.scaleTargetRef; if you choose to ignore these errors, turn validation off with --validate=false_

### Steps to Reproduce the Problem

1. Download the attached TXT  file.
2. Change the extension of the file to .yaml
3. Change directory in terminal to where the downloaded YAML file is.
4. Run the command "kubectl apply -f .\ms-scaledobject.yaml
[ms-scaledobject.txt](https://github.com/kedacore/http-add-on/files/7888758/ms-scaledobject.txt)

### Logs from KEDA HTTP operator

```
example
```

### What version of the KEDA HTTP Addon are you running?

Chart version: keda-add-ons-http-0.2.1, App version: 0.2.0

### Kubernetes Version

1.20

### Platform

Microsoft Azure

**Comment by tpiperatgod** [comment]
According to the [latest version](https://github.com/kedacore/http-add-on/blob/c211da9bd1ec400d4d2316f20176655eddeea59e/operator/api/v1alpha1/httpscaledobject_types.go#L90-L103), this field should be used like this:
```yaml
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: httpscaledobject
    namespace: app
spec:
    host: "abc.com"
    targetPendingRequests: 100 # should be here 
    scaleTargetRef:
        deployment: app-deployment
        service: app-service
        port: 443
        # targetPendingRequests: 100 # shouldn't be here
```
