### ISSUE TITLE
targetPendingRequests

### ISSUE THREAD

**Issue by avinash31d** [kedacore/http-add-on#371]
### Discussed in https://github.com/kedacore/http-add-on/discussions/330

<div type='discussions-op-text'>

<sup>Originally posted by **mikaelasanchez** November 24, 2021</sup>
Hello! I hope I'm posting this in the right place.

### Gateway Timeout
I'm trying to get a simple Hello World app working with KEDA and followed the instructions in the walkthrough page
Firstly, when I edit the ingress to point to `keda-add-ons-http-interceptor-proxy`, the pod starts up (good)
But then I receive a 504 Gateway Time-out error, instead of it showing "Hello World"
After a while, it does scale back to 0 (good)

Not sure what's going on here?

### targetPendingRequests
In addition, I'm getting this error:
![image](https://user-images.githubusercontent.com/4958440/143085012-bdb32cd3-078f-43db-83df-1b9ceeb1d3f3.png)

My YAML file:
```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: hello
spec:
    host: hello.127.0.0.1.nip.io
    scaleTargetRef:
        deployment: hello
        service: hello
        port: 80
        targetPendingRequests: 10
```

Thanks in advance :)</div>
