### ISSUE TITLE
HTTP add-on: Error in interceptor while waiting for the backend pod to be up and running

### ISSUE THREAD

**Issue by hgpepco** [kedacore/http-add-on#476]
Currently trying keda http-add-on v0.3. and keda v2.5.1 I am facing 2 issues,

1. No healthy upstream error for the first try and the subsequent tries, the request is served.(Updated the KEDA_CONDITION_WAIT_TIMEOUT)
2. In the interceptor I see this error when it need to wait for the backend to be up and running. Also below is the interceptor configuration.

`{"level":"error","ts":1655424772.5865734,"logger":"runProxyServer","caller":"interceptor/proxy_handlers.go:83","msg":"wait function failed, not forwarding request","error":"context marked done while waiting for deployment func-httptrigger-test to reach > 0 replicas (context canceled)","stacktrace":"main.newForwardingHandler.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/proxy_handlers.go:83\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\nmain.countMiddleware.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/middleware.go:48\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929"}`

Interceptor Configuration:
```yaml
       name: "keda-add-ons-http-interceptor"
        env:
        - name: KEDA_HTTP_ROUTING_TABLE_UPDATE_DURATION_MS
          value: "500"
        - name: KEDA_HTTP_CURRENT_NAMESPACE
          value: "keda"
        - name: KEDA_HTTP_PROXY_PORT
          value: "8080"
        - name: KEDA_HTTP_ADMIN_PORT
          value: "9090"
        - name: KEDA_HTTP_CONNECT_TIMEOUT
          value: "5s"
        - name: KEDA_HTTP_KEEP_ALIVE
          value: "1s"
        - name: KEDA_RESPONSE_HEADER_TIMEOUT
          value: "50s"
        - name: KEDA_CONDITION_WAIT_TIMEOUT
          value: "60s"
        - name: KEDA_HTTP_DEPLOYMENT_CACHE_POLLING_INTERVAL_MS
          value: "250"
        - name: KEDA_HTTP_FORCE_HTTP2
          value: "false"
        - name: KEDA_HTTP_MAX_IDLE_CONNS
          value: "100"
        - name: KEDA_HTTP_IDLE_CONN_TIMEOUT
          value: "90s"
        - name: KEDA_HTTP_TLS_HANDSHAKE_TIMEOUT
          value: "10s"
        - name: KEDA_HTTP_EXPECT_CONTINUE_TIMEOUT
          value: "1s"
```
