### ISSUE TITLE
Routing table only shows for the first deployment

### ISSUE THREAD

**Issue by unzld** [kedacore/http-add-on#482]
### Report

I have two deployments I wish to scale, a frontend (site front) and a backend (for API requests etc). For testing purposes these two are just simple containers that prints out hello world. I have two sets of deployments, services, ingress, and HTTPScaledObjects. I am also using ingress-nginx. I am able to scale any one of them if I remove the other.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: {{ .Values.interceptorPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: {{ .Values.interceptorPort }}
```

Here I just set `interceptorPort` to 8080 and `host` to `myhost.com`. What happens is that when I curl `https://myhost.com` or `https://myhost.com/api/` traffic goes to only one of them (whichever came first). When I inspect the keda-http-routing-table configmap I only see a single entry. 

```
{"myhost.com":{"Service":"frontend","Port":8080,"Deployment":"frontend","Namespace":"web","TargetPendingRequests":200}}
```

Again, whichever one came first. Frontend and backend at this stage is interchangeable, differing only in name and container ports.

### Expected Behavior

- Traffic routes to respective deployment/pods ie:
`curl https://myhost.com` routes to frontend deployment and,
`curl https://myhost.com/api/` routes to backend deployment.

- Two entries in the configmap routing table

### Actual Behavior

- Traffic routes to only one of the deployments, whichever got declared first. 
- Only one entry in the configmap routing table, whichever got declared first.
- Routing works as expected without the HTTP Add-on

### Steps to Reproduce the Problem

1. Declare two similar sets of deployments, services, ingress, HTTPScaledObject to represent frontend, backend
2. Both are in the same namespace as well as the keda-http-add-on (in my case it's named `web`)
3. Try routing traffic using curl

### Logs from KEDA HTTP operator

```
example
```

### What version of the KEDA HTTP Add-on are you running?

0.3.0

### Kubernetes Version

1.22

### Platform

Other

### Anything else?

The actual configs for the resources are pretty barebones. I can provide if needed.
