### ISSUE TITLE
Adding configuration for time required to scale deployments in

### ISSUE THREAD

**Issue by someshkoli** [kedacore/http-add-on#562]
Currently I believe there's not such configuration where we can tell how much time to wait for deployments to scale down to zero. 
Can someone point me to where exactly we have setup timeout loops ? 
Will raise a pr for this feature ^
### Use-Case
Have different types of workloads which require different scale down timeouts. 

Tell us more what you'd like to achieve

### Specification

Tell us in detail how this feature should work

**Comment by tomkerkhove** [comment]
KEDA Core has this as part of the ScaledObject for scaling to 0 as per `cooldownPeriod` so it should be feasible to do this.

For the rest, it's up to the HPA to define when to scale in if I'm not mistaken - Correct @JorTurFer / @zroubalik?

**Comment by tomkerkhove** [comment]
The request from @Kaitou786 in https://github.com/kedacore/http-add-on/discussions/550 is for scaling to 0 so cooldownPeriod should work.

**Comment by someshkoli** [comment]
Will raise a pr for this 🙌

**Comment by JorTurFer** [comment]
yeah, `cooldownPeriod` is for the scaling from/to 0, the rest of the scaling is modified by the advanced section of the HPA, in KEDA core we have support to it in the ScaledObject, maybe it's something we can expose here too

**Comment by tomkerkhove** [comment]
@JorTurFer Let's do on a feature-per-feature basis to avoid making it too complex and ensure it works properly with this add-on (ie scaling mechanics/scenarios, etc)

**Comment by holygrolli** [comment]
after trying this feature out with v0.4.0 I created a `HTTPScaledObject`
```
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
spec:
  host: host.mydomain.com
  replicas:
    max: 1
    min: 0
  scaleTargetRef:
    deployment: mydeployment
    port: 80
    service: mysvc
  scaledownPeriod: 600
  targetPendingRequests: 100
```
apparently the `cooldownPeriod` is never being put into the `ScaledObject`
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  maxReplicaCount: 1
  minReplicaCount: 0
  pollingInterval: 1
  scaleTargetRef:
    kind: Deployment
    name: mydeployment
  triggers:
  - metadata:
      host: host.mydomain.com
      scalerAddress: keda-add-ons-http-external-scaler.keda:9090
    type: external-push
```
did I miss something?
