### ISSUE TITLE
Scale more than one deployment per HTTPScaledObject

### ISSUE THREAD

**Issue by proligde** [kedacore/http-add-on#673]
First of all, a big thank you to the KEDA community: This is a great tool that has finally allowed me to scale all unused workloads down to zero and easily scale up on demand.

After implementing KEDA on several clusters, there is one feature I particularly miss: Since I use Helm, most of my projects consist of multiple deployments. When a project is inactive, I would like to scale all these deployments down and back up simultaneously, based on an HTTPScaledObject.

Right now my only option would be to consolidate all deployments into one, which is unrealistic, or I'd have to create more ScaledObjects for every interconnection that might never be inactive due to keepalive or metric traffic and so on.

However, this level of complexity could be avoided if I could just provide an array of deployments like so:

```
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: myScaledObject
spec:
  host: myhost.example.com
  targetPendingRequests: 1
  scaleTargetRef:
    deployments:
    - deploymentOne
    - deploymentTwo
    - deploymentThree
    service: myMainWebService
    port: 80
  replicas:
    min: 0
    max: 1
```

Or is this possible already and I was just unable to figure out, how?

Thanks in advance - Max
