### ISSUE TITLE
support for paths in HTTPScaledObject CRD

### ISSUE THREAD

**Issue by sammyyu** [kedacore/http-add-on#839]
### Proposal

Modification to CRD to support something like this:

```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: pui-dashboard
    namespace: pui-dashboard
spec:
    hosts:
      - myhost.com
    path: /service1
    targetPendingRequests: 2
    scaleTargetRef:
        deployment: service1
        service: service1
        port: 80
    replicas:
        min: 2
        max: 10
----
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: pui-dashboard
    namespace: pui-dashboard
spec:
    hosts:
      - myhost.com
    path: /service2
    targetPendingRequests: 2
    scaleTargetRef:
        deployment: service2
        service: service2
        port: 80
    replicas:
        min: 2
        max: 10


```

### Use-Case

Our application has a single host and based on the path points to different deployments 
using ingress something like this:
```

spec:
  rules:
  - host: myhost.com
    http:
      paths:
      - path: /servicea
        backend:
          serviceName: servicea
          servicePort: 80
      - path: /serviceb
        backend:
          serviceName: serviceb
          servicePort: 80

```

I would like to have something similar for CRD that the keda-add-ons-http-interceptor-proxy can properly redirect and scale appropriately based on host and path

### Is this a feature you are interested in implementing yourself?

No
