### ISSUE TITLE
add pause autoscaling

### ISSUE THREAD

**Issue by jchobantonov-runbuggy** [kedacore/http-add-on#840]
### Proposal

ScaledObject have ability to pause autoscaling in events where manual scaling is needed. HTTPScaledObject do not support the annotations that ScaledObject provides which are defined in ScaledObject yaml:

```
metadata:
  annotations:
    autoscaling.keda.sh/paused-replicas: "0"                # Optional. Use to pause autoscaling of objects
    autoscaling.keda.sh/paused: "true"                      # Optional. Use to pause autoscaling of objects explicitly
```

### Use-Case

If for some reason autoscaling do not behave as it should be (like external monitoring values are not right which could cause strange behavior etc) to have ability to temporary pause the autoscaling.

### Is this a feature you are interested in implementing yourself?

No
