### ISSUE TITLE
Not specifying hosts list makes interceptor proxy return "Not Found"

### ISSUE THREAD

**Issue by ShukantPal** [kedacore/http-add-on#849]
### Report

Following up on https://github.com/kedacore/http-add-on/issues/755, I was trying to configure my `HttpScaledObject` behind an nginx ingress using the HTTP interceptor in the `keda` namespace (keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local).

Everything was set up correctly except doing an HTTP request would return `Not Found`. My configuration was:

```yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: lindy-api-scaledobject
spec:
  scaleTargetRef:
    deployment: lindy-api
    service: lindy-api
    port: 80
  replicas:
    min: {{ .Values.hpa.minPods }}
    max: {{ .Values.hpa.maxPods }}
  targetPendingRequests: {{ .Values.hpa.targetPendingRequests }}
```

The following configuration worked
```yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: lindy-api-scaledobject
spec:
  hosts:
    - api.{{ .Values.deployEnv }}.lindy.ai
    - keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local:8080
  scaleTargetRef:
    deployment: lindy-api
    service: lindy-api
    port: 80
  replicas:
    min: {{ .Values.hpa.minPods }}
    max: {{ .Values.hpa.maxPods }}
  targetPendingRequests: {{ .Values.hpa.targetPendingRequests }}
```

But the `spec.hosts` field is supposed to be optional.

### Expected Behavior

If `spec.hosts` is unspecified, that HTTPScaledObject should accept all HTTP requests

### Actual Behavior

The KEDA HTTP operator fails to route requests

### Steps to Reproduce the Problem

Described in report

### HTTP Add-on Version

0.6.0

### Kubernetes Version

< 1.26

### Platform

Google Cloud
