### ISSUE TITLE
Support rewrote targets during path based routing

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/http-add-on#851]
### Proposal

Reverse proxies support rewriting the path before calling the next backend. 

Imagine this ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: potato.com
      http:
        paths:
          - path: /store(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: interceptor-svc
                port:
                  number: 8080
```

Requests to the interceptor won't contain the full path but the rewrote path, for example `https://potato.com/store/checkout` will be passed to the interceptor as `https://potato.com/checkout`.

The problem is that if we want to support path based routing in the interceptor, we need to maintain the pathPrefix. For example, this HTTPScaledObject doesn't work:

```
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: demo-http-sp
spec:
  hosts:
  - potato.com
  pathPrefixes:
  - /store
```

This won't work due to this removed prefix, and the same request (https://potato.com/store/checkout) returns 404 and generates an error like this the interceptor:
```bash
{"level":"error","ts":1702068375.455492,"logger":"LoggingMiddleware.RoutingMiddleware.StaticHandler","caller":"handler/static.go:36","msg":"Not Found","routingKey":"//potato.com/checkout/","namespacedNameError":"PANIC=value method k8s.io/apimachinery/pkg/types.NamespacedName.MarshalLog called using nil *NamespacedName pointer","stream":"<nil>","stacktrace":"github.com/kedacore/http-add-on/interceptor/handler.(*Static).ServeHTTP\n\tgithub.com/kedacore/http-add-on/interceptor/handler/static.go:36\ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP\n\tgithub.com/kedacore/http-add-on/interceptor/middleware/routing.go:46\ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP\n\tgithub.com/kedacore/http-add-on/interceptor/middleware/logging.go:42\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2936\nnet/http.(*conn).serve\n\tnet/http/server.go:1995"}
```

TBH, I'm not sure about the best approach here. Maybe we can introduce a custom header (via snippet) in the ingress with the original path (IDK if this is possible), or even better (but more complicated and worse for migration to the add-on), supporting the target-rewrite at interceptor level. 

This second option (supporting the rewrites within interceptor) allows users to maintain their current backends without any change as in that scenario, they would have to move the rewrite from ingress to interceptor and backends would continue without any change.

### Is this a feature you are interested in implementing yourself?

No
